[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
configs = {path = "../configs"}
app = {path = "../app"}
db = {path = "../db"}
tracing = "0.1"
tracing-appender = "0.2"
# tracing-log = "0.1"
tracing-subscriber = {version = "0.3", features = ["json", "env-filter", "local-time", "registry"]}
tokio = { version = "1.21.2", features = ["full"] }
axum = { version = "0.6", features = ["headers"] }
serde_json = "1.0.87"
