[http]
port=3321
[log]
stdout = true
log_level="info"
dir = "log"
file = "app_log"
[database]
link = 'postgresql://postgres:1@localhost/palyoh'
hmac_key="asd"
[jwt]
jwt_secret="se"
jwt_exp=123123
[system]
user_agent_parser = "config/regexes.yaml"
super_user=[]