[package]
name = "configs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
confique = "0.2.0"
once_cell = "1.15.0"
serde = {version = "1.0", features = ["derive"]}
